#!/usr/bin/env python3
"""Generate a conservative read-only Home Assistant Modbus YAML for Hitachi VRF.

This generator intentionally exposes raw registers first. It does not generate
write controls or climate entities because commissioning must confirm serial
settings, address base, function codes, and room mapping.
"""
from __future__ import annotations

import argparse
from pathlib import Path

STATIC = [
    (16, "model_code", "机种码", 300),
    (26, "system_no", "系统号", 300),
    (27, "indoor_address", "地址号", 300),
    (28, "power_status_raw", "开关状态原始值", 10),
    (29, "mode_status_raw", "模式状态原始值", 10),
    (30, "fan_status_raw", "风量状态原始值", 10),
    (31, "set_temp_integer", "设定温度整数", 10),
    (32, "set_humidity_raw", "设定湿度原始值", 30),
    (35, "alarm_code", "报警代码", 10),
    (37, "set_temp_half_raw", "设定温度半度标志", 10),
    (38, "outlet_temp_raw", "出风温度原始值", 15),
    (39, "room_temp_raw", "回风温度原始值", 15),
]


def sensor_block(name: str, unique_id: str, address: int, scan: int) -> str:
    return f"""      - name: "{name}"
        unique_id: {unique_id}
        slave: !secret hitachi_modbus_slave
        address: {address}
        input_type: holding
        data_type: uint16
        scan_interval: {scan}
"""


def generate(units: int, connection_type: str) -> str:
    if not 1 <= units <= 160:
        raise ValueError("units must be between 1 and 160")
    lines = [
        "# Generated by scripts/generate_hitachi_ha_yaml.py",
        "# READ-ONLY COMMISSIONING CONFIGURATION - verify addresses before enabling writes.",
        "modbus:",
        "  - name: hitachi_hvac",
        f"    type: {connection_type}",
        "    host: !secret hitachi_modbus_host",
        "    port: !secret hitachi_modbus_port",
        "    timeout: 5",
        "    message_wait_milliseconds: 100",
        "    sensors:",
    ]
    lines.append(sensor_block("日立转换器_室内机数量", "hitachi_converter_unit_count", 4997, 60).rstrip())
    lines.append(sensor_block("日立转换器_可控状态", "hitachi_converter_ready_raw", 4998, 5).rstrip())
    for y in range(units):
        base = 40000 + 91 * y
        for offset, suffix, cn, scan in STATIC:
            lines.append(sensor_block(
                f"日立室内机{y}_{cn}",
                f"hitachi_unit_{y}_{suffix}",
                base + offset,
                scan,
            ).rstrip())
    lines.extend([
        "",
        "# Notes:",
        "# 1. The supplied point table calls these protocol register addresses.",
        "#    If 4998/4997 do not return plausible values, confirm whether the",
        "#    converter or serial server expects an address offset of -1.",
        "# 2. Do not write register 4999 automatically.",
        "# 3. Do not enable control until 4998 reads 1 and the Y-to-room mapping is complete.",
    ])
    return "\n".join(lines) + "\n"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--units", type=int, default=4, help="Expected indoor units (1-160)")
    p.add_argument("--type", choices=["rtuovertcp", "tcp"], default="rtuovertcp")
    p.add_argument("--output", type=Path)
    args = p.parse_args()
    data = generate(args.units, args.type)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(data, encoding="utf-8")
    else:
        print(data, end="")


if __name__ == "__main__":
    main()
